#!/bin/bash

# pip installation requires setuptools...
aptitude install -y python python-dev python-setuptools
wget -qO- https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python
# ...but debian's is ancient
aptitude purge python-setuptools

pip install virtualenv setuptools

