#!/bin/bash

aptitude install -y python python-dev python-distribute
curl -qO https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python
# python get-pip.py
pip install virtualenv

# rm get-pip.py
